[database]
current = 2
root = data
filename_template = graph_{db_number}.db

[database_names]
; 1 maps to linear algebra (线性代数)
1 = linear_algebra
2 = probability_and_mathematical_statistics

[database_paths]
1 = data/graph.db
2 = data/graph2.db
